# Generated by Django 3.2.20 on 2023-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description_short', models.CharField(max_length=500, verbose_name='Short Description')),
                ('description_long', models.CharField(blank=True, max_length=3000, verbose_name='Long Description')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
            ],
        ),
    ]
