# Generated by Django 4.2.3 on 2023-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=1),
        ),
    ]
