# Generated by Django 4.2.3 on 2023-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_images_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
